import type { Metadata } from "next";
import { Modal } from "@/components/ui/modal/modal";
import { ProfileHeader } from "@/components/ProfileHeader";
import { SidebarCg } from "@/components/layout-components/SidebarCg";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Modal>
        <div className="flex gap-3 p-2 min-h-[87vh] max-h-[87vh]">
          <SidebarCg />
          <div className="flex flex-col gap-2 w-full overflow-y-scroll pr-2">
            <ProfileHeader />
            {children}
          </div>
        </div>
      </Modal>
    </div>
  );
}
