// design-tokens/parsed-tokens.js
const tokens = require('./design-tokens'); // This file is generated by Style Dictionary

// --- Helper: Format keys for Tailwind (lowercase, replace spaces with hyphens)
function formatKey(key) {
  return key.toLowerCase().replace(/\s+/g, '-');
}

// --- Parse Color Categories
function parseColorCategory(category) {
  if (!tokens[category]) return {};
  return Object.fromEntries(
    Object.entries(tokens[category]).map(([key, token]) => [
      formatKey(key),
      token.value,
    ])
  );
}

const backgrounds   = parseColorCategory("Backgrounds");
const colors        = parseColorCategory("Colors");
const color         = parseColorCategory("Color");
const neutralColors = parseColorCategory("Neutral-colors");
const brandColors   = parseColorCategory("Brand-colors");
const supportColors = parseColorCategory("Support-colors");

const allColors = {
  ...backgrounds,
  ...colors,
  ...color,
  ...neutralColors,
  ...brandColors,
  ...supportColors,
};

// --- Parse Strokes (for border widths)
// Assumes strokes are under tokens.Strokes.card
let strokes = {};
if (tokens.Strokes && tokens.Strokes.card) {
  strokes = Object.fromEntries(
    Object.entries(tokens.Strokes.card).map(([key, token]) => [
      formatKey(key),
      token.value + 'px'
    ])
  );
}

// --- Parse Radius (for border radius)
let radius = {};
if (tokens.Radius) {
  radius = Object.fromEntries(
    Object.entries(tokens.Radius).map(([key, token]) => [
      formatKey(key),
      token.value + 'px'
    ])
  );
}

// --- Parse Text Styles (full style objects)
// The Figma textStyles export is an array of objects. We want to capture all properties.
function parseTextStyles() {
  const textStyles = {};
  if (!tokens.textStyles) return textStyles;
  tokens.textStyles.forEach(style => {
    const key = formatKey(style.name); // e.g., "H1" becomes "h1"

    // Compute fontSize in rem (assuming 16px base)
    const fontSize = style.fontSize ? `${style.fontSize / 16}rem` : undefined;

    // Use fontFamily and fontWeight as provided, with a conversion for common names.
    const fontFamily = style.fontFamily || 'sans-serif';
    const fontWeight = (function(weight) {
      if (!weight) return undefined;
      const lower = weight.toLowerCase();
      if (lower === 'bold') return '700';
      if (lower === 'semibold') return '600';
      if (lower === 'medium') return '500';
      if (lower === 'regular') return '400';
      return weight;
    })(style.fontWeight);

    // Convert letterSpacing from percent to em (if letterSpacing exists)
    const letterSpacing = style.letterSpacing && style.letterSpacing.value != null
      ? `${style.letterSpacing.value / 100}em`
      : undefined;

    // Figma may not export lineHeight; compute a default if needed (e.g., 1.2 or based on a ratio)
    const lineHeight = style.lineHeight ? `${style.lineHeight / style.fontSize}` : '1.2';

    // Map textCase to CSS text-transform; "ORIGINAL" becomes "none"
    const textTransform = style.textCase && style.textCase.toLowerCase() === "original"
      ? "none"
      : style.textCase && style.textCase.toLowerCase();

    textStyles[key] = {
      fontSize,
      fontFamily,
      fontWeight,
      letterSpacing,
      lineHeight,
      textTransform,
    };
  });
  return textStyles;
}

const textStyles = parseTextStyles();

// Export all parsed tokens
module.exports = {
  colors: allColors,
  strokes,
  radius,
  textStyles, // Full text style objects keyed by style name (e.g., "h1", "h2", etc.)
};
