version: '3.8'

services:
  agency-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fc-agency-service
    restart: always
    depends_on:
      - findcare-postgres
    ports:
      - "8081:8081"
    networks:
      - findcare-network
    volumes:
      - ../shared-db/docker-entrypoint-initdb.d:/app/db/migration
    environment:
      SPRING_DATASOURCE_MASTER_URL: jdbc:postgresql://findcare-postgres:5432/master_db
      SPRING_DATASOURCE_MASTER_USERNAME: admin
      SPRING_DATASOURCE_MASTER_PASSWORD: root123
      SPRING_FLYWAY_URL: jdbc:postgresql://findcare-postgres:5432/master_db
      SPRING_FLYWAY_USER: admin
      SPRING_FLYWAY_PASSWORD: root123
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration/master

  findcare-postgres:
    extends:
      file: ../shared-db/docker-compose.yml
      service: postgres

networks:
  findcare-network:
    name: findcare-network
    external: true