/**
 * Do not edit directly, this file was auto-generated.
 */

module.exports = {
  Backgrounds: {
    main: {
      type: "color",
      value: "#FDFCFC",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#ffffff",
      },
      name: "BackgroundsMain",
      attributes: {
        category: "Backgrounds",
        type: "main",
      },
      path: ["Backgrounds", "main"],
    },
    "main-2": {
      type: "color",
      value: "#f6f8f8",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#f6f8f8",
      },
      name: "BackgroundsMain2",
      attributes: {
        category: "Backgrounds",
        type: "main-2",
      },
      path: ["Backgrounds", "main-2"],
    },
    "big card": {
      type: "color",
      value: "#f7f8f8",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#f7f8f8",
      },
      name: "BackgroundsBigCard",
      attributes: {
        category: "Backgrounds",
        type: "big card",
      },
      path: ["Backgrounds", "big card"],
    },
    "small card": {
      type: "color",
      value: "#f8fbfb",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#f8fbfb",
      },
      name: "BackgroundsSmallCard",
      attributes: {
        category: "Backgrounds",
        type: "small card",
      },
      path: ["Backgrounds", "small card"],
    },
    "small card - orange": {
      type: "color",
      value: "#fbfaf8",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#fbfaf8",
      },
      name: "BackgroundsSmallCardOrange",
      attributes: {
        category: "Backgrounds",
        type: "small card - orange",
      },
      path: ["Backgrounds", "small card - orange"],
    },
  },
  Colors: {
    grey: {
      type: "color",
      value: "#5a6a72",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#5a6a72",
      },
      name: "ColorsGrey",
      attributes: {
        category: "Colors",
        type: "grey",
      },
      path: ["Colors", "grey"],
    },
    "grey-darker": {
      type: "color",
      value: "#424957",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#424957",
      },
      name: "ColorsGreyDarker",
      attributes: {
        category: "Colors",
        type: "grey-darker",
      },
      path: ["Colors", "grey-darker"],
    },
    "logo-colors-icon": {
      type: "color",
      value: "#424957",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#424957",
      },
      name: "ColorsLogoColorsIcon",
      attributes: {
        category: "Colors",
        type: "logo-colors-icon",
      },
      path: ["Colors", "logo-colors-icon"],
    },
  },
  Color: {
    "bg-card": {
      type: "color",
      value: "#f1f3f4",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#f1f3f4",
      },
      name: "ColorBgCard",
      attributes: {
        category: "Color",
        type: "bg-card",
      },
      path: ["Color", "bg-card"],
    },
    "test color 2": {
      type: "color",
      value: "#8d9da5",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#8d9da5",
      },
      name: "ColorTestColor2",
      attributes: {
        category: "Color",
        type: "test color 2",
      },
      path: ["Color", "test color 2"],
    },
  },
  Strokes: {
    card: {
      xs: {
        type: "number",
        value: 0.5,
        filePath: "design.variables.tokens.json",
        isSource: true,
        original: {
          type: "number",
          value: 0.5,
        },
        name: "StrokesCardXs",
        attributes: {
          category: "Strokes",
          type: "card",
          item: "xs",
        },
        path: ["Strokes", "card", "xs"],
      },
      small: {
        type: "number",
        value: 0.800000011920929,
        filePath: "design.variables.tokens.json",
        isSource: true,
        original: {
          type: "number",
          value: 0.800000011920929,
        },
        name: "StrokesCardSmall",
        attributes: {
          category: "Strokes",
          type: "card",
          item: "small",
        },
        path: ["Strokes", "card", "small"],
      },
      big: {
        type: "number",
        value: 1,
        filePath: "design.variables.tokens.json",
        isSource: true,
        original: {
          type: "number",
          value: 1,
        },
        name: "StrokesCardBig",
        attributes: {
          category: "Strokes",
          type: "card",
          item: "big",
        },
        path: ["Strokes", "card", "big"],
      },
      Number: {
        type: "number",
        value: 0,
        filePath: "design.variables.tokens.json",
        isSource: true,
        original: {
          type: "number",
          value: 0,
        },
        name: "StrokesCardNumber",
        attributes: {
          category: "Strokes",
          type: "card",
          item: "Number",
        },
        path: ["Strokes", "card", "Number"],
      },
    },
  },
  Radius: {
    xs: {
      type: "number",
      value: 4,
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "number",
        value: 4,
      },
      name: "RadiusXs",
      attributes: {
        category: "Radius",
        type: "xs",
      },
      path: ["Radius", "xs"],
    },
    small: {
      type: "number",
      value: 8,
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "number",
        value: 8,
      },
      name: "RadiusSmall",
      attributes: {
        category: "Radius",
        type: "small",
      },
      path: ["Radius", "small"],
    },
    regular: {
      type: "number",
      value: 12,
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "number",
        value: 12,
      },
      name: "RadiusRegular",
      attributes: {
        category: "Radius",
        type: "regular",
      },
      path: ["Radius", "regular"],
    },
    big: {
      type: "number",
      value: 16,
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "number",
        value: 16,
      },
      name: "RadiusBig",
      attributes: {
        category: "Radius",
        type: "big",
      },
      path: ["Radius", "big"],
    },
  },
  "Neutral-colors": {
    White: {
      type: "color",
      value: "#ffffff",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#ffffff",
      },
      name: "NeutralColorsWhite",
      attributes: {
        category: "Neutral-colors",
        type: "White",
      },
      path: ["Neutral-colors", "White"],
    },
    "Neutral 1": {
      type: "color",
      value: "#f5f5f5",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#f5f5f5",
      },
      name: "NeutralColorsNeutral1",
      attributes: {
        category: "Neutral-colors",
        type: "Neutral 1",
      },
      path: ["Neutral-colors", "Neutral 1"],
    },
    "Neutral 2": {
      type: "color",
      value: "#f2f2f2",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#f2f2f2",
      },
      name: "NeutralColorsNeutral2",
      attributes: {
        category: "Neutral-colors",
        type: "Neutral 2",
      },
      path: ["Neutral-colors", "Neutral 2"],
    },
    "Neutral 3": {
      type: "color",
      value: "#e6e6e6",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#e6e6e6",
      },
      name: "NeutralColorsNeutral3",
      attributes: {
        category: "Neutral-colors",
        type: "Neutral 3",
      },
      path: ["Neutral-colors", "Neutral 3"],
    },
    "Neutral 4": {
      type: "color",
      value: "#d9d9d9",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#d9d9d9",
      },
      name: "NeutralColorsNeutral4",
      attributes: {
        category: "Neutral-colors",
        type: "Neutral 4",
      },
      path: ["Neutral-colors", "Neutral 4"],
    },
    "Neutral 5": {
      type: "color",
      value: "#cccccc",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#cccccc",
      },
      name: "NeutralColorsNeutral5",
      attributes: {
        category: "Neutral-colors",
        type: "Neutral 5",
      },
      path: ["Neutral-colors", "Neutral 5"],
    },
    "Neutral 6": {
      type: "color",
      value: "#bfbfbf",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#bfbfbf",
      },
      name: "NeutralColorsNeutral6",
      attributes: {
        category: "Neutral-colors",
        type: "Neutral 6",
      },
      path: ["Neutral-colors", "Neutral 6"],
    },
    "Neutral 7": {
      type: "color",
      value: "#999999",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#999999",
      },
      name: "NeutralColorsNeutral7",
      attributes: {
        category: "Neutral-colors",
        type: "Neutral 7",
      },
      path: ["Neutral-colors", "Neutral 7"],
    },
    "Neutral 8": {
      type: "color",
      value: "#808080",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#808080",
      },
      name: "NeutralColorsNeutral8",
      attributes: {
        category: "Neutral-colors",
        type: "Neutral 8",
      },
      path: ["Neutral-colors", "Neutral 8"],
    },
    "Neutral 9": {
      type: "color",
      value: "#333333",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#333333",
      },
      name: "NeutralColorsNeutral9",
      attributes: {
        category: "Neutral-colors",
        type: "Neutral 9",
      },
      path: ["Neutral-colors", "Neutral 9"],
    },
    "Neutral 10": {
      type: "color",
      value: "#262626",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#262626",
      },
      name: "NeutralColorsNeutral10",
      attributes: {
        category: "Neutral-colors",
        type: "Neutral 10",
      },
      path: ["Neutral-colors", "Neutral 10"],
    },
    "Neutral 11": {
      type: "color",
      value: "#191919",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#191919",
      },
      name: "NeutralColorsNeutral11",
      attributes: {
        category: "Neutral-colors",
        type: "Neutral 11",
      },
      path: ["Neutral-colors", "Neutral 11"],
    },
    "Neutral 12": {
      type: "color",
      value: "#0d0d0d",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#0d0d0d",
      },
      name: "NeutralColorsNeutral12",
      attributes: {
        category: "Neutral-colors",
        type: "Neutral 12",
      },
      path: ["Neutral-colors", "Neutral 12"],
    },
    Black: {
      type: "color",
      value: "#000000",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#000000",
      },
      name: "NeutralColorsBlack",
      attributes: {
        category: "Neutral-colors",
        type: "Black",
      },
      path: ["Neutral-colors", "Black"],
    },
  },
  "Brand-colors": {
    Main: {
      type: "color",
      value: "#fa5300",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#fa5300",
      },
      name: "BrandColorsMain",
      attributes: {
        category: "Brand-colors",
        type: "Main",
      },
      path: ["Brand-colors", "Main"],
    },
    "Brand 2": {
      type: "color",
      value: "#ff6619",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#ff6619",
      },
      name: "BrandColorsBrand2",
      attributes: {
        category: "Brand-colors",
        type: "Brand 2",
      },
      path: ["Brand-colors", "Brand 2"],
    },
    "Brand 4": {
      type: "color",
      value: "#ff884c",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#ff884c",
      },
      name: "BrandColorsBrand4",
      attributes: {
        category: "Brand-colors",
        type: "Brand 4",
      },
      path: ["Brand-colors", "Brand 4"],
    },
    "Brand 5": {
      type: "color",
      value: "#ff9966",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#ff9966",
      },
      name: "BrandColorsBrand5",
      attributes: {
        category: "Brand-colors",
        type: "Brand 5",
      },
      path: ["Brand-colors", "Brand 5"],
    },
    "Brand 3": {
      type: "color",
      value: "#ff7733",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#ff7733",
      },
      name: "BrandColorsBrand3",
      attributes: {
        category: "Brand-colors",
        type: "Brand 3",
      },
      path: ["Brand-colors", "Brand 3"],
    },
    "Brand 6": {
      type: "color",
      value: "#ffaa80",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#ffaa80",
      },
      name: "BrandColorsBrand6",
      attributes: {
        category: "Brand-colors",
        type: "Brand 6",
      },
      path: ["Brand-colors", "Brand 6"],
    },
    "Brand 7": {
      type: "color",
      value: "#ffbb99",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#ffbb99",
      },
      name: "BrandColorsBrand7",
      attributes: {
        category: "Brand-colors",
        type: "Brand 7",
      },
      path: ["Brand-colors", "Brand 7"],
    },
    "Brand 8": {
      type: "color",
      value: "#ffccb2",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#ffccb2",
      },
      name: "BrandColorsBrand8",
      attributes: {
        category: "Brand-colors",
        type: "Brand 8",
      },
      path: ["Brand-colors", "Brand 8"],
    },
    "Brand 9": {
      type: "color",
      value: "#ffddcc",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#ffddcc",
      },
      name: "BrandColorsBrand9",
      attributes: {
        category: "Brand-colors",
        type: "Brand 9",
      },
      path: ["Brand-colors", "Brand 9"],
    },
  },
  "Support-colors": {
    "Color 1": {
      type: "color",
      value: "#007aff",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#007aff",
      },
      name: "SupportColorsColor1",
      attributes: {
        category: "Support-colors",
        type: "Color 1",
      },
      path: ["Support-colors", "Color 1"],
    },
    "Color 2": {
      type: "color",
      value: "#fca827",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#fca827",
      },
      name: "SupportColorsColor2",
      attributes: {
        category: "Support-colors",
        type: "Color 2",
      },
      path: ["Support-colors", "Color 2"],
    },
    "Color 3": {
      type: "color",
      value: "#ff2d55",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#ff2d55",
      },
      name: "SupportColorsColor3",
      attributes: {
        category: "Support-colors",
        type: "Color 3",
      },
      path: ["Support-colors", "Color 3"],
    },
    "Color 4": {
      type: "color",
      value: "#00b1cc",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#00b1cc",
      },
      name: "SupportColorsColor4",
      attributes: {
        category: "Support-colors",
        type: "Color 4",
      },
      path: ["Support-colors", "Color 4"],
    },
    "Color 5": {
      type: "color",
      value: "#6210c1",
      filePath: "design.variables.tokens.json",
      isSource: true,
      original: {
        type: "color",
        value: "#6210c1",
      },
      name: "SupportColorsColor5",
      attributes: {
        category: "Support-colors",
        type: "Color 5",
      },
      path: ["Support-colors", "Color 5"],
    },
  },
  fileName: "SaaS High fidelity",
  textStyles: [
    {
      name: "H1",
      fontFamily: "Jura",
      fontWeight: "Bold",
      fontSize: 48,
      letterSpacing: {
        unit: "PERCENT",
        value: -3,
        filePath: "design.textStyles.tokens.json",
        isSource: true,
      },
      textCase: "ORIGINAL",
    },
    {
      name: "H2",
      fontFamily: "Plus Jakarta Sans",
      fontWeight: "SemiBold",
      fontSize: 40,
      letterSpacing: {
        unit: "PERCENT",
        value: -3,
        filePath: "design.textStyles.tokens.json",
        isSource: true,
      },
      textCase: "ORIGINAL",
    },
    {
      name: "H3",
      fontFamily: "Plus Jakarta Sans",
      fontWeight: "SemiBold",
      fontSize: 32,
      letterSpacing: {
        unit: "PERCENT",
        value: -3,
        filePath: "design.textStyles.tokens.json",
        isSource: true,
      },
      textCase: "ORIGINAL",
    },
    {
      name: "H4",
      fontFamily: "Plus Jakarta Sans",
      fontWeight: "SemiBold",
      fontSize: 28,
      letterSpacing: {
        unit: "PERCENT",
        value: -3,
        filePath: "design.textStyles.tokens.json",
        isSource: true,
      },
      textCase: "ORIGINAL",
    },
    {
      name: "H5",
      fontFamily: "Plus Jakarta Sans",
      fontWeight: "Medium",
      fontSize: 24,
      letterSpacing: {
        unit: "PERCENT",
        value: -3,
        filePath: "design.textStyles.tokens.json",
        isSource: true,
      },
      textCase: "ORIGINAL",
    },
    {
      name: "H6",
      fontFamily: "Plus Jakarta Sans",
      fontWeight: "Medium",
      fontSize: 20,
      letterSpacing: {
        unit: "PERCENT",
        value: 0,
        filePath: "design.textStyles.tokens.json",
        isSource: true,
      },
      textCase: "ORIGINAL",
    },
    {
      name: "Tagline",
      fontFamily: "Plus Jakarta Sans",
      fontWeight: "Medium",
      fontSize: 14,
      letterSpacing: {
        unit: "PERCENT",
        value: 1,
        filePath: "design.textStyles.tokens.json",
        isSource: true,
      },
      textCase: "ORIGINAL",
    },
    {
      name: "Regular_text",
      fontFamily: "Plus Jakarta Sans",
      fontWeight: "Regular",
      fontSize: 16,
      letterSpacing: {
        unit: "PERCENT",
        value: 0,
        filePath: "design.textStyles.tokens.json",
        isSource: true,
      },
      textCase: "ORIGINAL",
    },
    {
      name: "Regular_text-thicker",
      fontFamily: "Plus Jakarta Sans",
      fontWeight: "Medium",
      fontSize: 16,
      letterSpacing: {
        unit: "PERCENT",
        value: 0,
        filePath: "design.textStyles.tokens.json",
        isSource: true,
      },
      textCase: "ORIGINAL",
    },
    {
      name: "Small_text",
      fontFamily: "Plus Jakarta Sans",
      fontWeight: "Regular",
      fontSize: 14,
      letterSpacing: {
        unit: "PERCENT",
        value: 0,
        filePath: "design.textStyles.tokens.json",
        isSource: true,
      },
      textCase: "ORIGINAL",
    },
    {
      name: "XSmall_text",
      fontFamily: "Plus Jakarta Sans",
      fontWeight: "Regular",
      fontSize: 12,
      letterSpacing: {
        unit: "PERCENT",
        value: -3,
        filePath: "design.textStyles.tokens.json",
        isSource: true,
      },
      textCase: "ORIGINAL",
    },
  ],
};
