import type { Metadata } from "next";
import NavbarComponent from "./components/NavbarComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"min-h-screen m-0"}>
        <div className="min-h-screen flex ">
          <NavbarComponent />
          <main className="w-full">{children}</main>
        </div>
      </body>
    </html>
  );
}
