import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import NavbarComponent from "./components/NavbarComponent";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className={`min-h-screen m-0 ${inter.className}`}>
        <div className="min-h-screen flex">
          {/* <Navbar /> */}
          <NavbarComponent />
          <main className="w-full">{children}</main>
        </div>
      </body>
    </html>
  );
}
