version: '3.8'

services:
  caregiver-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fc-caregiver-service
    restart: always
    depends_on:
      - findcare-postgres
    ports:
      - "8082:8082"
    networks:
      - findcare-network
    environment:
      SPRING_DATASOURCE_MASTER_URL: jdbc:postgresql://findcare-postgres:5432/master_db
      SPRING_DATASOURCE_MASTER_USERNAME: admin
      SPRING_DATASOURCE_MASTER_PASSWORD: root123
      SERVER_PORT: 8082
      # Flyway is disabled as we manage it through agency-service
      SPRING_FLYWAY_ENABLED: false

  findcare-postgres:
    extends:
      file: ../shared-db/docker-compose.yml
      service: postgres

networks:
  findcare-network:
    name: findcare-network
    external: true