import type { Metadata } from "next";
import { Modal } from "@/components/ui/modal/modal";
import { CaregiverForm } from "@/components/add-caregiver/CaregiverForm";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Modal routePath="/caregivers">
        <div className="flex gap-3 p-2 min-h-[87vh] max-h-[87vh]">
          <CaregiverForm />;
        </div>
      </Modal>
    </div>
  );
}
