import { Modal } from "@/components/ui/modal/modal";
import { ProfileHeader } from "@/components/ProfileHeader";
import React from "react";

<<<<<<< HEAD
interface ProfileParams {
  id: string;
  cr_Id: string;
}

export default async function ProfileLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<ProfileParams>;
}) {
  const resolvedParams = await params;
  const dynamicPath = `/tenant/${resolvedParams.id}/clients`;
=======

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define the correct params type for Next.js App Router
interface ClientProfileLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({
  children,
}: ClientProfileLayoutProps) {

  const dynamicPath = `/tenant/1/clients`;
>>>>>>> bd9da10c3159df2668fbd9e686f0d1090893b11d

  return (
    <div>
      <Modal routePath={dynamicPath}>
        <div className="flex gap-3 p-2 min-h-[87vh] max-h-[87vh]">
          {/* Replace with the appropriate sidebar for clients if needed */}
          <div className="flex flex-col gap-2 w-full overflow-y-scroll pr-2">
            <ProfileHeader />
            {children}
          </div>
        </div>
      </Modal>
    </div>
  );
}
