/**
 * @fileoverview Client Profile Layout Component
 * Provides the layout structure for the client profile section including modal and sidebar
 */

import React from 'react';
import type { Metadata } from "next";
import { Modal } from "@/components/ui/modal/modal";
import { ProfileHeader } from "@/components/ProfileHeader";
import { SidebarClient } from "@/components/layout-components/SidebarClient";

/**
 * Metadata configuration for the page
 * @type {Metadata}
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Props interface for the RootLayout component
 * @interface RootLayoutProps
 */
interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    id: string;    // Tenant ID
    cr_Id: string; // Client ID
  };
}

/**
 * Root layout component for the client profile section
 * @param {RootLayoutProps} props - Component props
 * @param {React.ReactNode} props.children - Child components to render
 * @param {Object} props.params - URL parameters
 * @returns {JSX.Element} Rendered layout component
 */
export default function RootLayout({
  children,
  params,
}: Readonly<RootLayoutProps>): React.ReactElement {
  const dynamicPath: string = `/tenant/${params.id}/clients`;

  return (
    <div>
      <Modal routePath={dynamicPath}>
        <div className="flex gap-4 p-2 min-h-[87vh] max-h-[87vh]">
          <SidebarClient />
          <div className="flex flex-col gap-2 w-full overflow-y-scroll pr-4 pb-8">
            <ProfileHeader profileHeading="Client Profile" />
            {children}
          </div>
        </div>
      </Modal>
    </div>
  );
}
