import type { Metadata } from "next";
import { Modal } from "@/components/ui/modal/modal";
import { MatchesTable } from "@/components/table/MatchesTable";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <div>
      <Modal routePath="/tenant/1/filla-spot/" width={80}>
        <div className="flex gap-3 p-2 min-h-[87vh] max-h-[87vh]">
          <MatchesTable />
        </div>
      </Modal>
    </div>
  );
}
