# ========== Azure Production setup ==========
services:
  household-service:
    build: .
    container_name: household-service
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "household-service"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://fc-household-db.postgres.database.azure.com:5432/household?sslmode=require"
      SPRING_DATASOURCE_USERNAME: "householddbadmin"
      SPRING_DATASOURCE_PASSWORD: "Findcare_admin_pwd"
      SPRING_FLYWAY_ENABLED: true
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: true
      SERVER_PORT: 8080
